services:
  - type: web
    name: gnanastack-api
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.12.0
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://gnanastack-frontend.onrender.com
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false

  - type: web
    name: gnanastack-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 22.12.0
      - key: VITE_API_BASE_URL
        value: https://gnanastack-api.onrender.com/api/v1
